server:
  port: 3088

spring:

    datasource:
         url: jdbc:mysql://localhost:3306/livraria?useUnicode=yes&serverTimezone=UTC&characterEncoding=UTF-8
         username: root
         password: Fiap1234
         initialization-mode: always

    jpa:
        hibernate:
          ddl-auto: create
          show-sql: true
          format_sql: true


    jwt:
    secret: f1aPs3cr37
    expire: 5






